version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:19.0.0

    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
         command: |
          google-chrome --version
          chromedriver --version
         name: Check install
      - checkout

      - run:
         name: Installing dependencies 
         command: npm install

      - run:
         name: Building the source code
         command: npm run build
   
      - run
         name: Build test cases
         command: npm run test

#      - run:
#         name: Building the source code
#         command: |
#            sudo apt update
#            sudo apt install snapd
#            sudo systemctl enable snapd.service
#            sudo systemctl start snapd.service
#            sudo snap refresh
#            sudo snap install chromium-browser -y
#            export CHROME_BIN='/usr/bin/chromium-browser'
#            npm test --no-watch --no-progress --browsers=ChromeHeadless

      - store_artifacts:
         path: /home/circleci/project/dist/electronic-voting-ui/
         destination: electronic-voting-ui
