version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:19.0.0

    steps:
      - checkout

      - run:
         name: Installing dependencies 
         command: npm install

      - run:
         name: Building the source code
         command: npm run build

      - run:
         name: Building the source code
         command: npm test --no-watch --no-progress --browsers=ChromeHeadless

      - store_artifacts:
         path: /home/circleci/project/dist/electronic-voting-ui/
         destination: electronic-voting-ui
