version: 2.1
jobs:
  build-and-test-ui:
    docker:
      - image: circleci/node:latest
        environment:
          CHROME_BIN: /usr/bin/google-chrome

    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      - run:
         name: Installing dependencies 
         command: npm install

      - run:
         name: Building the source code
         command: npm run build

      - run:
        name: docker build
        command: docker build -t electronic-voting-ui .
   
      - run:
         name: Building the source code
         command: |
            npm test --no-watch --no-progress --browsers=ChromeHeadlessCI

      - store_artifacts:
         path: /home/circleci/project/dist/electronic-voting-ui/
         destination: electronic-voting-ui


workflows:
  sample:
    jobs:
      - build-and-test-ui:
          filters:
            branches:
              only:
                - master
                - TEC-45
